feat(service-agent): debugging system improvements
jolocom/interactions-demo pull request #33
Opened 2021-06-25 07:44 UTC by serg-temchenko

2021-06-25 12:04 UTC, mnzaki requested changes

2021-06-25 12:04 UTC, mnzaki commented on service_agent/package.json
> +    "start:debug": "nodemon --watch \"src/*.ts\" \"src/**/*.ts\" \"node_modules/*jolocom*/**/*.js\" --ext ts,js --ignore src/**/*.spec.ts --exec \"node --inspect -r ts-node/register ./src/index.ts --
There's already a nodemon.json file that contains most of this configuration, please use that

2021-06-25 12:04 UTC, mnzaki commented on service_agent/package.json
>      "debug": "DEBUG=1 nodemon",
please also use this start script or change it, as it's confusing to have both `debug` and `start:debug`

2021-07-01 09:16 UTC, serg-temchenko commented
@mnzaki I've made improvements after code review, please check it now.

2021-07-01 10:40 UTC, mnzaki approved these changes

2021-07-01 10:41 UTC, merged